### ISSUE TITLE
customize_changeset_uuid paramater being appended to urls after close customizer

### ISSUE THREAD

**Issue by a3rev** [a3rev/responsi#1]
responsi customize issue -  Version 6.5.9.12 and WordPress v 4.8.0

Customizer close button appends customize_changeset_uuid paramater to all public facing URL's

**Comment by a3rev** [comment]
Issue closed with `[commit version 6.5.9.13](https://github.com/a3rev/responsi/commit/ac6060c0d6d7c87b5fe8ee394415c57527971a69)`

**Comment by bassam2** [comment]
what the solve

**Comment by cmarabate** [comment]
I am having the same issue.

Could you possibly give me a PHP snippet I could put in my functions.php file to fix this instead of editing the core WordPress files.

Thanks,
