### ISSUE TITLE
On dropdown the items have a text decoration underline

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/responsi#65]
@mrkunau Hello Dat. While work on this site: https://dorep.a3de.info/ I see that the dropdown menu items have a text decoration underline. We don't need it on the dropdown menu.

![screenshot](https://gyazo.com/a13d201c91597e381d413f0ae6bd5acd.png)

**Comment by a3rev** [comment]
Fixed in [release 7.9.0](https://github.com/a3rev/responsi/releases/tag/7.9.0)
