### ISSUE TITLE
Move Header Extender Mobile Style options into framework

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/responsi#67]
@mrkunau Hi Dat.

I have used Inline Header on this site: https://dorep.a3de.info/ and notice we don't have any option for Mobile navigation. I spoke with Steve and we want all of the Header Extender Mobile menu options in the framework for use with: 

- Framework Mobile Menu / dropdown

- Header Extender Mobile Menu / Dropdown

- Inline Header Mobile menu / Dropdown

**Comment by a3rev** [comment]
These options were moved from header extender to the framework in [version 7.9.0](https://github.com/a3rev/responsi/releases/tag/7.9.0)
