### ISSUE TITLE
Set default blocks for new post, page like default theme of WP

### ISSUE THREAD

**Issue by alextuan** [a3rev/responsi#68]
When add new post or page need to have default blocks like default theme of WP made

https://gyazo.com/ae9bb9b2ee5c5178d9cd4fdb2c0f5f5b

Also find way to define background color from Gutenberg edit page so that it like background color will apply on frontend, it helps admin can set color for text or any blocks to show good with background color on page

**Comment by a3rev** [comment]
Released in [version 7.8.3](https://github.com/a3rev/responsi/releases/tag/7.8.3)
