### ISSUE TITLE
Sliders arrow and pager have a conflict with Responsi

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/responsi#70]
@mrkunau Hello Dat. I notice a issue with almost any sliders I try to use with Responsi. The arrows and the pager show strange. I install a block from other developer Getwid Blocks and when try to use their slider block the occur appear. Using other theme the slider show fine. Also when using Elementor (slider, testimonial with sliders etc) same issue appear.

**Getwid Media and Title Block**
![screenshot](https://gyazo.com/14ef84479847b7c0064c9e71f243fb55.png)

**Getwid Image Slider Block**
![screenshot](https://gyazo.com/60c7d2175638f85349d29e994c4340b0.png)

**Elementor Testimonials Slider**
![screenshot](https://gyazo.com/3a2445f9a9733973da6045ff72f5af36.png)

**Comment by a3rev** [comment]
Conflict with Getwid slider icons fixed in [version 7.9.1](https://github.com/a3rev/responsi/releases/tag/7.9.1)
