### ISSUE TITLE
Core quote block has a conflict with Responsi

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/responsi#71]
@mrkunau Hello Dat. Another issue I just saw with Steve it's with core quote block. Using other theme they show and work like expected but when install responsi they seems to not work.
The text will not go Italic and the quote icon it's not showing.

**Here I used Getwid theme with the core block quote:**

![screenshot](https://gyazo.com/634d9b0f37c26cb6692386532b0d5c7c.png)

**Here it's used Responsi and core quote block**

![screenshot](https://gyazo.com/008ee7f2e2e4d481c0d0a999e25309e9.png)

**Comment by a3rev** [comment]
Fixed in [version 7.9.1](https://github.com/a3rev/responsi/releases/tag/7.9.1)
