### ISSUE TITLE
Issue with H tags block after WordPress 5.9 RC4 update

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/responsi#77]
@mrkunau Hello Dat. After I update the Responsi framework with the new wp version 5.9 RC4 I see a issue with default  H tag block. Seems they show the theme default style and not the style set on customizer.
You can check it here: https://randragencies.com.au/

![screenshot](https://gyazo.com/809f8bc9b1891734decf091976349659.png)
---------
![screenshot](https://gyazo.com/1cfa4c94df5431acb2b79fe3e67abe66.png)
---------
![screenshot](https://gyazo.com/57f502c7a5dd5c339dba1b5f0ac80665.png)

**Comment by a3rev** [comment]
Patch released in [version 8.3.2](https://github.com/a3rev/responsi/releases/tag/8.3.2)
